CREATE TABLE IF NOT EXISTS PEER_STATUS
(
    CHANNEL_TYPE VARCHAR                  NOT NULL,
    PEER         VARCHAR                  NOT NULL,
    PEER_STATUS  VARCHAR                  NOT NULL,
    CAUSE        VARCHAR,
    ADDRESS      VARCHAR,
    PORT         VARCHAR,
    TIME         VARCHAR,
    _INSTANCE    VARCHAR                  NOT NULL,
    _TIMESTAMP   TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (CHANNEL_TYPE, PEER, _INSTANCE)
);

CREATE TABLE IF NOT EXISTS PEER_STATUS_LOG
(
    CHANNEL_TYPE VARCHAR                  NOT NULL,
    PEER         VARCHAR                  NOT NULL,
    PEER_STATUS  VARCHAR                  NOT NULL,
    CAUSE        VARCHAR,
    ADDRESS      VARCHAR                  NOT NULL,
    PORT         VARCHAR,
    TIME         VARCHAR,
    _INSTANCE    VARCHAR                  NOT NULL,
    _TIMESTAMP   TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (CHANNEL_TYPE, PEER, ADDRESS, _INSTANCE)
);

CREATE TABLE IF NOT EXISTS INVALID_EVENT_LOG
(
    EVENT               VARCHAR                  NOT NULL,
    EVENT_TV            TIMESTAMP WITH TIME ZONE NOT NULL,
    SEVERITY            VARCHAR                  NOT NULL,
    SERVICE             VARCHAR                  NOT NULL,
    EVENT_VERSION       LONG                     NOT NULL,
    ACCOUNT_ID          VARCHAR                  NOT NULL,
    SESSION_ID          VARCHAR                  NOT NULL,
    LOCAL_ADDRESS       VARCHAR                  NOT NULL,
    REMOTE_ADDRESS      VARCHAR                  NOT NULL,
    ATTEMPTED_TRANSPORT VARCHAR,
    MODULE              VARCHAR,
    SESSION_TV          VARCHAR,
    CHALLENGE           VARCHAR,
    RECEIVED_CHALLENGE  VARCHAR,
    RECEIVED_HASH       VARCHAR,
    _INSTANCE           VARCHAR                  NOT NULL,
    _TIMESTAMP          TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (EVENT, SERVICE, ACCOUNT_ID, REMOTE_ADDRESS, _INSTANCE)
);

CREATE TABLE IF NOT EXISTS REGISTRY
(
    CHANNEL_TYPE VARCHAR,
    USERNAME     VARCHAR                  NOT NULL,
    DOMAIN       VARCHAR                  NOT NULL,
    STATUS       VARCHAR                  NOT NULL,
    CAUSE        VARCHAR                  NOT NULL,
    _INSTANCE    VARCHAR                  NOT NULL,
    _TIMESTAMP   TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (USERNAME, DOMAIN, _INSTANCE)
);

CREATE TABLE IF NOT EXISTS DEVICE_STATE
(
    DEVICE     VARCHAR NOT NULL,
    STATE      VARCHAR NOT NULL,
    _INSTANCE  VARCHAR NOT NULL,
    _TIMESTAMP TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (DEVICE, _INSTANCE)
);
