SELECT _INSTANCE,EVENT,SERVICE,ACCOUNT_ID,REMOTE_ADDRESS
FROM INVALID_EVENT_LOG
GROUP BY _INSTANCE,EVENT,SERVICE,ACCOUNT_ID,REMOTE_ADDRESS
ORDER BY _INSTANCE,EVENT,SERVICE,LENGTH(ACCOUNT_ID),ACCOUNT_ID,REMOTE_ADDRESS;