SELECT T2.*
FROM (SELECT _INSTANCE, PEER, COUNT(PEER) AS COUNT
      FROM PEER_STATUS_LOG
      WHERE PEER_STATUS = 'Registered'
        AND LENGTH(ADDRESS) > 0
      GROUP BY _INSTANCE, PEER
      HAVING COUNT > 1) T1
INNER JOIN PEER_STATUS_LOG T2
ON T1._INSTANCE = T2._INSTANCE AND T1.PEER = T2.PEER
WHERE LENGTH(T2.ADDRESS) > 0
ORDER BY T2._INSTANCE,LENGTH(T2.PEER),T2.PEER,T2.ADDRESS;
